# _config.yml
title: "Jarosław Mastalerczyk"
description: "Portfolio"
baseurl: ""
url: "https://jaromasta.github.io/"

# Podstawowe ustawienia
theme: minima
author:
  name: Jarosław Mastalerczyk
  email: jaroslawmastalerczyk@gmail.com

# Dodatkowe pluginy
plugins:
  - jekyll-seo-tag
  - jekyll-feed
